export const mapData = [
	{
		areaCode: 1,
		title: "서울",
		mapy: 37.554715,
		mapx: 126.970796,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "강남구", code: 1 },
			{ name: "강동구", code: 2 },
			{ name: "강북구", code: 3 },
			{ name: "강서구", code: 4 },
			{ name: "관악구", code: 5 },
			{ name: "광진구", code: 6 },
			{ name: "구로구", code: 7 },
			{ name: "금천구", code: 8 },
			{ name: "노원구", code: 9 },
			{ name: "도봉구", code: 10 },
			{ name: "동대문구", code: 11 },
			{ name: "동작구", code: 12 },
			{ name: "마포구", code: 13 },
			{ name: "서대문구", code: 14 },
			{ name: "서초구", code: 15 },
			{ name: "성동구", code: 16 },
			{ name: "성북구", code: 17 },
			{ name: "송파구", code: 18 },
			{ name: "양천구", code: 19 },
			{ name: "영등포구", code: 20 },
			{ name: "용산구", code: 21 },
			{ name: "은평구", code: 22 },
			{ name: "종로구", code: 23 },
			{ name: "중구", code: 24 },
			{ name: "중랑구", code: 25 },
		],
	},
	{
		areaCode: 2,
		title: "인천",
		mapy: 37.4562557,
		mapx: 126.7052062,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "강화군", code: 1 },
			{ name: "계양구", code: 2 },
			{ name: "미추홀구", code: 3 },
			{ name: "남동구", code: 4 },
			{ name: "동구", code: 5 },
			{ name: "부평구", code: 6 },
			{ name: "서구", code: 7 },
			{ name: "연수구", code: 8 },
			{ name: "옹진군", code: 9 },
			{ name: "중구", code: 10 },
		],
	},
	{
		areaCode: 3,
		title: "대전",
		mapy: 36.332326,
		mapx: 127.434211,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "대덕구", code: 1 },
			{ name: "동구", code: 2 },
			{ name: "서구", code: 3 },
			{ name: "유성구", code: 4 },
			{ name: "중구", code: 5 },
		],
	},
	{
		areaCode: 4,
		title: "대구",
		mapy: 35.876083,
		mapx: 128.596031,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "남구", code: 1 },
			{ name: "달서구", code: 2 },
			{ name: "달성군", code: 3 },
			{ name: "동구", code: 4 },
			{ name: "북구", code: 5 },
			{ name: "서구", code: 6 },
			{ name: "수성구", code: 7 },
			{ name: "중구", code: 8 },
			{ name: "군위군", code: 9 },
		],
	},
	{
		areaCode: 5,
		title: "광주",
		mapy: 35.1653428,
		mapx: 126.9092003,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "광산구", code: 1 },
			{ name: "남구", code: 2 },
			{ name: "동구", code: 3 },
			{ name: "북구", code: 4 },
			{ name: "서구", code: 5 },
		],
	},
	{
		areaCode: 6,
		title: "부산",
		mapy: 35.114465,
		mapx: 129.039348,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "강서구", code: 1 },
			{ name: "금정구", code: 2 },
			{ name: "기장군", code: 3 },
			{ name: "남구", code: 4 },
			{ name: "동구", code: 5 },
			{ name: "동래구", code: 6 },
			{ name: "부산진구", code: 7 },
			{ name: "북구", code: 8 },
			{ name: "사상구", code: 9 },
			{ name: "사하구", code: 10 },
			{ name: "서구", code: 11 },
			{ name: "수영구", code: 12 },
			{ name: "연제구", code: 13 },
			{ name: "영도구", code: 14 },
			{ name: "중구", code: 15 },
			{ name: "해운대구", code: 16 },
		],
	},
	{
		areaCode: 7,
		title: "울산",
		mapy: 35.551431,
		mapx: 129.138506,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "중구", code: 1 },
			{ name: "남구", code: 2 },
			{ name: "동구", code: 3 },
			{ name: "북구", code: 4 },
			{ name: "울주군", code: 5 },
		],
	},
	{
		areaCode: 8,
		title: "세종",
		mapy: 36.4799919,
		mapx: 127.2890511,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "세종특별자치시", code: 1 },
		],
	},
	{
		areaCode: 31,
		title: "경기",
		mapy: 37.2634485,
		mapx: 127.0286427,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "가평군", code: 1 },
			{ name: "고양시", code: 2 },
			{ name: "과천시", code: 3 },
			{ name: "광명시", code: 4 },
			{ name: "광주시", code: 5 },
			{ name: "구리시", code: 6 },
			{ name: "군포시", code: 7 },
			{ name: "김포시", code: 8 },
			{ name: "남양주시", code: 9 },
			{ name: "동두천시", code: 10 },
			{ name: "부천시", code: 11 },
			{ name: "성남시", code: 12 },
			{ name: "수원시", code: 13 },
			{ name: "시흥시", code: 14 },
			{ name: "안산시", code: 15 },
			{ name: "안성시", code: 16 },
			{ name: "안양시", code: 17 },
			{ name: "양주시", code: 18 },
			{ name: "양평군", code: 19 },
			{ name: "여주시", code: 20 },
			{ name: "연천군", code: 21 },
			{ name: "오산시", code: 22 },
			{ name: "용인시", code: 23 },
			{ name: "의왕시", code: 24 },
			{ name: "의정부시", code: 25 },
		],
	},
	{
		areaCode: 32,
		title: "강원",
		mapy: 37.7637815,
		mapx: 128.9016465,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "강릉시", code: 1 },
			{ name: "고성군", code: 2 },
			{ name: "동해시", code: 3 },
			{ name: "삼척시", code: 4 },
			{ name: "속초시", code: 5 },
			{ name: "양구군", code: 6 },
			{ name: "양양군", code: 7 },
			{ name: "영월군", code: 8 },
			{ name: "원주시", code: 9 },
			{ name: "인제군", code: 10 },
			{ name: "정선군", code: 11 },
			{ name: "철원군", code: 12 },
			{ name: "춘천시", code: 13 },
			{ name: "태백시", code: 14 },
			{ name: "평창군", code: 15 },
			{ name: "홍천군", code: 16 },
			{ name: "화천군", code: 17 },
			{ name: "횡성군", code: 18 },
		],
	},
	{
		areaCode: 33,
		title: "충북",
		mapy: 36.6358093,
		mapx: 127.4913338,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "괴산군", code: 1 },
			{ name: "단양군", code: 2 },
			{ name: "보은군", code: 3 },
			{ name: "영동군", code: 4 },
			{ name: "옥천군", code: 5 },
			{ name: "음성군", code: 6 },
			{ name: "제천시", code: 7 },
			{ name: "진천군", code: 8 },
			{ name: "청주시", code: 10 },
			{ name: "충주시", code: 11 },
			{ name: "증평군", code: 12 },
		],
	},
	{
		areaCode: 34,
		title: "충남",
		mapy: 36.659387,
		mapx: 126.672996,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "공주시", code: 1 },
			{ name: "금산군", code: 2 },
			{ name: "논산시", code: 3 },
			{ name: "당진시", code: 4 },
			{ name: "보령시", code: 5 },
			{ name: "부여군", code: 6 },
			{ name: "서산시", code: 7 },
			{ name: "서천군", code: 8 },
			{ name: "아산시", code: 9 },
			{ name: "예산군", code: 11 },
			{ name: "천안시", code: 12 },
			{ name: "청양군", code: 13 },
			{ name: "태안군", code: 14 },
			{ name: "홍성군", code: 15 },
			{ name: "계룡시", code: 16 },
		],
	},
	{
		areaCode: 35,
		title: "경북",
		mapy: 36.576106,
		mapx: 128.50591,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "경산시", code: 1 },
			{ name: "경주시", code: 2 },
			{ name: "고령군", code: 3 },
			{ name: "구미시", code: 4 },
			{ name: "김천시", code: 6 },
			{ name: "문경시", code: 7 },
			{ name: "봉화군", code: 8 },
			{ name: "상주시", code: 9 },
			{ name: "성주군", code: 10 },
			{ name: "안동시", code: 11 },
			{ name: "영덕군", code: 12 },
			{ name: "영양군", code: 13 },
			{ name: "영주시", code: 14 },
			{ name: "영천시", code: 15 },
			{ name: "예천군", code: 16 },
			{ name: "울릉군", code: 17 },
			{ name: "울진군", code: 18 },
			{ name: "의성군", code: 19 },
			{ name: "청도군", code: 20 },
			{ name: "청송군", code: 21 },
			{ name: "칠곡군", code: 22 },
			{ name: "포항시", code: 23 },
		],
	},
	{
		areaCode: 36,
		title: "경남",
		mapy: 35.2378276,
		mapx: 128.6919111,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "거제시", code: 1 },
			{ name: "거창군", code: 2 },
			{ name: "고성군", code: 3 },
			{ name: "김해시", code: 4 },
			{ name: "남해군", code: 5 },
			{ name: "밀양시", code: 7 },
			{ name: "사천시", code: 8 },
			{ name: "산청군", code: 9 },
			{ name: "양산시", code: 10 },
			{ name: "의령군", code: 12 },
			{ name: "진주시", code: 13 },
			{ name: "창녕군", code: 15 },
			{ name: "창원시", code: 16 },
			{ name: "통영시", code: 17 },
			{ name: "하동군", code: 18 },
			{ name: "함안군", code: 19 },
			{ name: "함양군", code: 20 },
			{ name: "합천군", code: 21 },
		],
	},
	{
		areaCode: 37,
		title: "전북",
		mapy: 35.8203535,
		mapx: 127.1087805,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "고창군", code: 1 },
			{ name: "군산시", code: 2 },
			{ name: "김제시", code: 3 },
			{ name: "남원시", code: 4 },
			{ name: "무주군", code: 5 },
			{ name: "부안군", code: 6 },
			{ name: "순창군", code: 7 },
			{ name: "완주군", code: 8 },
			{ name: "익산시", code: 9 },
			{ name: "임실군", code: 10 },
			{ name: "장수군", code: 11 },
			{ name: "전주시", code: 12 },
			{ name: "정읍시", code: 13 },
			{ name: "진안군", code: 14 },
		],
	},
	{
		areaCode: 38,
		title: "전남",
		mapy: 34.8162186,
		mapx: 126.4629242,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "강진군", code: 1 },
			{ name: "고흥군", code: 2 },
			{ name: "곡성군", code: 3 },
			{ name: "광양시", code: 4 },
			{ name: "구례군", code: 5 },
			{ name: "나주시", code: 6 },
			{ name: "담양군", code: 7 },
			{ name: "목포시", code: 8 },
			{ name: "무안군", code: 9 },
			{ name: "보성군", code: 10 },
			{ name: "순천시", code: 11 },
			{ name: "신안군", code: 12 },
			{ name: "여수시", code: 13 },
			{ name: "영광군", code: 16 },
			{ name: "영암군", code: 17 },
			{ name: "완도군", code: 18 },
			{ name: "장성군", code: 19 },
			{ name: "장흥군", code: 20 },
			{ name: "진도군", code: 21 },
			{ name: "함평군", code: 22 },
			{ name: "해남군", code: 23 },
			{ name: "화순군", code: 24 },
		],
	},
	{
		areaCode: 39,
		title: "제주",
		mapy: 33.5070772,
		mapx: 126.4934311,
		regions: [
			{ name: "전체", code: 0 },
			{ name: "서귀포시", code: 3 },
			{ name: "제주시", code: 4 },
		],
	},
];
