services:
  database:
    container_name: befreedb
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: befree
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - test_network

  web:
  container_name: befreeapi
  restart: on-failure
  build:
    context: ./
    dockerfile: dockerfile
  ports:
  - "8085:8085"
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://befreedb:3306/befree?useUnicode=true&characterEncoding=UTF-8&characterSetResult=UTF8&useSSL=false&allowPublicKeyRetrieval=true
    SPRING_DATASOURCE_USERNAME: "root"
    SPRING_DATASOURCE_PASSWORD: "1234"
  depends_on:
  - database
  networks:
  - test_network

  react:
    container_name: myreact
    restart: on-failure
    image: hyojin0515/befree:latest
    ports:
      - "3000:80"
    depends_on:
      - web
    networks:
      - test_network

networks:
  test_network: